
services:

  digibanter.web:
    image: ${DOCKER_REGISTRY-}digibanter.web
    container_name: digibanter.web
    build:
      context: .
      dockerfile: DigiBanter.Web/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081


  digibanter.api:
    image: ${DOCKER_REGISTRY-}digibanter.api
    container_name: digibanter.api
    build:
      context: .
      dockerfile: DigiBanter.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=5000
      - ASPNETCORE_HTTPS_PORTS=5001











