

using AutoMapper;
using ParsLinks.Api.Services;
using ParsLinks.DataAccess.DbContext;
using ParsLinks.Domain.Entities;
using ParsLinks.Shared.Dto.Response;
using ParsLinks.Shared.Models;
using ParsLinks.Shared.ResultWrapper;
using Microsoft.EntityFrameworkCore;

public class PodcastService : IPodcastService
{
    private readonly List<PodcastResponse> podcastList;

    public PodcastService()
    {
        podcastList = [  new PodcastResponse(Guid.NewGuid(), DateTime.Now, "https://themes.pixelwars.org/podcasty/demo-01/wp-content/uploads/sites/2/2020/11/b-02-1-550x550.jpg", "Perhaps, but perhaps your civilization is merely the sewer of an even greater society above you! I feel like I was mauled by Jesus. Stop! Don’t shoot fire stick in space canoe! Cause explosive decompression!\r\n\r\nWell, let’s just dump it in the sewer and say we delivered it. Fry, you can’t just sit here in the dark listening to classical music. The alien mothership is in orbit here. If we can hit that bullseye, the rest of the dominoes will fall like a house of cards. Checkmate.\r\n\r\nFatal. Daddy Bender, we’re hungry. And so we say goodbye to our beloved pet, Nibbler, who’s gone to a place where I, too, hope one day to go. The toilet. Well, thanks to the Internet, I’m now bored with sex. Is there a place on the web that panders to my lust for violence?\r\n\r\n", "Episode 06: Rise of Nomad Destinations"),
    new PodcastResponse(Guid.NewGuid(), DateTime.Now, "https://themes.pixelwars.org/podcasty/demo-01/wp-content/uploads/sites/2/2024/01/show-03-768x768.jpg", "Perhaps, but perhaps your civilization is merely the sewer of an even greater society above you! I feel like I was mauled by Jesus. Stop! Don’t shoot fire stick in space canoe! Cause explosive decompression!\r\n\r\nWell, let’s just dump it in the sewer and say we delivered it. Fry, you can’t just sit here in the dark listening to classical music. The alien mothership is in orbit here. If we can hit that bullseye, the rest of the dominoes will fall like a house of cards. Checkmate.\r\n\r\nFatal. Daddy Bender, we’re hungry. And so we say goodbye to our beloved pet, Nibbler, who’s gone to a place where I, too, hope one day to go. The toilet. Well, thanks to the Internet, I’m now bored with sex. Is there a place on the web that panders to my lust for violence?\r\n\r\n", "Episode 07: Goodbye boring, hello adventure"),
    new PodcastResponse(Guid.NewGuid(), DateTime.Now, "https://themes.pixelwars.org/podcasty/demo-01/wp-content/uploads/sites/2/2020/09/b-03-550x550.jpg", "Perhaps, but perhaps your civilization is merely the sewer of an even greater society above you! I feel like I was mauled by Jesus. Stop! Don’t shoot fire stick in space canoe! Cause explosive decompression!\r\n\r\nWell, let’s just dump it in the sewer and say we delivered it. Fry, you can’t just sit here in the dark listening to classical music. The alien mothership is in orbit here. If we can hit that bullseye, the rest of the dominoes will fall like a house of cards. Checkmate.\r\n\r\nFatal. Daddy Bender, we’re hungry. And so we say goodbye to our beloved pet, Nibbler, who’s gone to a place where I, too, hope one day to go. The toilet. Well, thanks to the Internet, I’m now bored with sex. Is there a place on the web that panders to my lust for violence?\r\n\r\n", "Episode 04: The Digital Nomad Lifestyle Facts"),
    new PodcastResponse(Guid.NewGuid(), DateTime.Now, "https://themes.pixelwars.org/podcasty/demo-01/wp-content/uploads/sites/2/2020/09/b-04-550x550.jpg", "Perhaps, but perhaps your civilization is merely the sewer of an even greater society above you! I feel like I was mauled by Jesus. Stop! Don’t shoot fire stick in space canoe! Cause explosive decompression!\r\n\r\nWell, let’s just dump it in the sewer and say we delivered it. Fry, you can’t just sit here in the dark listening to classical music. The alien mothership is in orbit here. If we can hit that bullseye, the rest of the dominoes will fall like a house of cards. Checkmate.\r\n\r\nFatal. Daddy Bender, we’re hungry. And so we say goodbye to our beloved pet, Nibbler, who’s gone to a place where I, too, hope one day to go. The toilet. Well, thanks to the Internet, I’m now bored with sex. Is there a place on the web that panders to my lust for violence?\r\n\r\n", "Episode 03: Dating As a Digital Nomad"),
    new PodcastResponse(Guid.NewGuid(), DateTime.Now, "https://themes.pixelwars.org/podcasty/demo-01/wp-content/uploads/sites/2/2020/09/b-06-550x550.jpg", "Perhaps, but perhaps your civilization is merely the sewer of an even greater society above you! I feel like I was mauled by Jesus. Stop! Don’t shoot fire stick in space canoe! Cause explosive decompression!\r\n\r\nWell, let’s just dump it in the sewer and say we delivered it. Fry, you can’t just sit here in the dark listening to classical music. The alien mothership is in orbit here. If we can hit that bullseye, the rest of the dominoes will fall like a house of cards. Checkmate.\r\n\r\nFatal. Daddy Bender, we’re hungry. And so we say goodbye to our beloved pet, Nibbler, who’s gone to a place where I, too, hope one day to go. The toilet. Well, thanks to the Internet, I’m now bored with sex. Is there a place on the web that panders to my lust for violence?\r\n\r\n", "Episode 02: Getting Rid Of Time Consuming Habits"),
    new PodcastResponse(Guid.NewGuid(), DateTime.Now, "https://themes.pixelwars.org/podcasty/demo-01/wp-content/uploads/sites/2/2020/11/b-02-1-550x550.jpg", "Perhaps, but perhaps your civilization is merely the sewer of an even greater society above you! I feel like I was mauled by Jesus. Stop! Don’t shoot fire stick in space canoe! Cause explosive decompression!\r\n\r\nWell, let’s just dump it in the sewer and say we delivered it. Fry, you can’t just sit here in the dark listening to classical music. The alien mothership is in orbit here. If we can hit that bullseye, the rest of the dominoes will fall like a house of cards. Checkmate.\r\n\r\nFatal. Daddy Bender, we’re hungry. And so we say goodbye to our beloved pet, Nibbler, who’s gone to a place where I, too, hope one day to go. The toilet. Well, thanks to the Internet, I’m now bored with sex. Is there a place on the web that panders to my lust for violence?\r\n\r\n", "Episode 06: Rise of Nomad Destinations"),
    new PodcastResponse(Guid.NewGuid(), DateTime.Now, "https://themes.pixelwars.org/podcasty/demo-01/wp-content/uploads/sites/2/2020/11/ahmetoz_van_gogh_style_adba5b8a-7c99-4218-972c-911812166326-550x550.png", "Perhaps, but perhaps your civilization is merely the sewer of an even greater society above you! I feel like I was mauled by Jesus. Stop! Don’t shoot fire stick in space canoe! Cause explosive decompression!\r\n\r\nWell, let’s just dump it in the sewer and say we delivered it. Fry, you can’t just sit here in the dark listening to classical music. The alien mothership is in orbit here. If we can hit that bullseye, the rest of the dominoes will fall like a house of cards. Checkmate.\r\n\r\nFatal. Daddy Bender, we’re hungry. And so we say goodbye to our beloved pet, Nibbler, who’s gone to a place where I, too, hope one day to go. The toilet. Well, thanks to the Internet, I’m now bored with sex. Is there a place on the web that panders to my lust for violence?\r\n\r\n", "Episode 02: Getting Rid Of Time Consuming Habits"),
    new PodcastResponse(Guid.NewGuid(), DateTime.Now, "https://themes.pixelwars.org/podcasty/demo-01/wp-content/uploads/sites/2/2020/09/amanda-souza-PPTiicBrVU4-unsplash-550x550.jpg", "Perhaps, but perhaps your civilization is merely the sewer of an even greater society above you! I feel like I was mauled by Jesus. Stop! Don’t shoot fire stick in space canoe! Cause explosive decompression!\r\n\r\nWell, let’s just dump it in the sewer and say we delivered it. Fry, you can’t just sit here in the dark listening to classical music. The alien mothership is in orbit here. If we can hit that bullseye, the rest of the dominoes will fall like a house of cards. Checkmate.\r\n\r\nFatal. Daddy Bender, we’re hungry. And so we say goodbye to our beloved pet, Nibbler, who’s gone to a place where I, too, hope one day to go. The toilet. Well, thanks to the Internet, I’m now bored with sex. Is there a place on the web that panders to my lust for violence?\r\n\r\n", "Episode 06: Rise of Nomad Destinations"),
    new PodcastResponse(Guid.NewGuid(), DateTime.Now, "https://themes.pixelwars.org/podcasty/demo-01/wp-content/uploads/sites/2/2020/09/b-06-300x300.jpg", "Perhaps, but perhaps your civilization is merely the sewer of an even greater society above you! I feel like I was mauled by Jesus. Stop! Don’t shoot fire stick in space canoe! Cause explosive decompression!\r\n\r\nWell, let’s just dump it in the sewer and say we delivered it. Fry, you can’t just sit here in the dark listening to classical music. The alien mothership is in orbit here. If we can hit that bullseye, the rest of the dominoes will fall like a house of cards. Checkmate.\r\n\r\nFatal. Daddy Bender, we’re hungry. And so we say goodbye to our beloved pet, Nibbler, who’s gone to a place where I, too, hope one day to go. The toilet. Well, thanks to the Internet, I’m now bored with sex. Is there a place on the web that panders to my lust for violence?\r\n\r\n", "Episode 07: Goodbye boring, hello adventure"),
    new PodcastResponse(Guid.NewGuid(), DateTime.Now, "https://themes.pixelwars.org/podcasty/demo-01/wp-content/uploads/sites/2/2020/09/nathan-dumlao-g-De0Zd2hZ0-unsplash-550x550.jpg", "Perhaps, but perhaps your civilization is merely the sewer of an even greater society above you! I feel like I was mauled by Jesus. Stop! Don’t shoot fire stick in space canoe! Cause explosive decompression!\r\n\r\nWell, let’s just dump it in the sewer and say we delivered it. Fry, you can’t just sit here in the dark listening to classical music. The alien mothership is in orbit here. If we can hit that bullseye, the rest of the dominoes will fall like a house of cards. Checkmate.\r\n\r\nFatal. Daddy Bender, we’re hungry. And so we say goodbye to our beloved pet, Nibbler, who’s gone to a place where I, too, hope one day to go. The toilet. Well, thanks to the Internet, I’m now bored with sex. Is there a place on the web that panders to my lust for violence?\r\n\r\n", "Episode 04: The Digital Nomad Lifestyle Facts"),
    new PodcastResponse(Guid.NewGuid(), DateTime.Now, "https://themes.pixelwars.org/podcasty/demo-01/wp-content/uploads/sites/2/2020/09/louis-hansel-shotsoflouis-GW0xfjw3IMg-unsplash-550x550.jpg", "Perhaps, but perhaps your civilization is merely the sewer of an even greater society above you! I feel like I was mauled by Jesus. Stop! Don’t shoot fire stick in space canoe! Cause explosive decompression!\r\n\r\nWell, let’s just dump it in the sewer and say we delivered it. Fry, you can’t just sit here in the dark listening to classical music. The alien mothership is in orbit here. If we can hit that bullseye, the rest of the dominoes will fall like a house of cards. Checkmate.\r\n\r\nFatal. Daddy Bender, we’re hungry. And so we say goodbye to our beloved pet, Nibbler, who’s gone to a place where I, too, hope one day to go. The toilet. Well, thanks to the Internet, I’m now bored with sex. Is there a place on the web that panders to my lust for violence?\r\n\r\n", "Episode 03: Dating As a Digital Nomad"),
    new PodcastResponse(Guid.NewGuid(), DateTime.Now, "https://themes.pixelwars.org/podcasty/demo-01/wp-content/uploads/sites/2/2020/09/dan-gold-xlNqmgDDYp0-unsplash-550x550.jpg", "Perhaps, but perhaps your civilization is merely the sewer of an even greater society above you! I feel like I was mauled by Jesus. Stop! Don’t shoot fire stick in space canoe! Cause explosive decompression!\r\n\r\nWell, let’s just dump it in the sewer and say we delivered it. Fry, you can’t just sit here in the dark listening to classical music. The alien mothership is in orbit here. If we can hit that bullseye, the rest of the dominoes will fall like a house of cards. Checkmate.\r\n\r\nFatal. Daddy Bender, we’re hungry. And so we say goodbye to our beloved pet, Nibbler, who’s gone to a place where I, too, hope one day to go. The toilet. Well, thanks to the Internet, I’m now bored with sex. Is there a place on the web that panders to my lust for violence?\r\n\r\n", "Episode 02: Getting Rid Of Time Consuming Habits"),
    
            new PodcastResponse(Guid.NewGuid(), DateTime.Now, "https://themes.pixelwars.org/podcasty/demo-01/wp-content/uploads/sites/2/2020/09/b-07.jpg", "Perhaps, but perhaps your civilization is merely the sewer of an even greater society above you! I feel like I was mauled by Jesus. Stop! Don’t shoot fire stick in space canoe! Cause explosive decompression!\r\n\r\nWell, let’s just dump it in the sewer and say we delivered it. Fry, you can’t just sit here in the dark listening to classical music. The alien mothership is in orbit here. If we can hit that bullseye, the rest of the dominoes will fall like a house of cards. Checkmate.\r\n\r\nFatal. Daddy Bender, we’re hungry. And so we say goodbye to our beloved pet, Nibbler, who’s gone to a place where I, too, hope one day to go. The toilet. Well, thanks to the Internet, I’m now bored with sex. Is there a place on the web that panders to my lust for violence?\r\n\r\n", "Episode 07: Goodbye boring, hello adventure"),
    new PodcastResponse(Guid.NewGuid(), DateTime.Now, "https://themes.pixelwars.org/podcasty/demo-01/wp-content/uploads/sites/2/2020/09/b-04-1-550x550.jpg", "Perhaps, but perhaps your civilization is merely the sewer of an even greater society above you! I feel like I was mauled by Jesus. Stop! Don’t shoot fire stick in space canoe! Cause explosive decompression!\r\n\r\nWell, let’s just dump it in the sewer and say we delivered it. Fry, you can’t just sit here in the dark listening to classical music. The alien mothership is in orbit here. If we can hit that bullseye, the rest of the dominoes will fall like a house of cards. Checkmate.\r\n\r\nFatal. Daddy Bender, we’re hungry. And so we say goodbye to our beloved pet, Nibbler, who’s gone to a place where I, too, hope one day to go. The toilet. Well, thanks to the Internet, I’m now bored with sex. Is there a place on the web that panders to my lust for violence?\r\n\r\n", "Episode 04: The Digital Nomad Lifestyle Facts"),
    new PodcastResponse(Guid.NewGuid(), DateTime.Now, "https://themes.pixelwars.org/podcasty/demo-01/wp-content/uploads/sites/2/2020/11/b-02-550x550.jpg", "Perhaps, but perhaps your civilization is merely the sewer of an even greater society above you! I feel like I was mauled by Jesus. Stop! Don’t shoot fire stick in space canoe! Cause explosive decompression!\r\n\r\nWell, let’s just dump it in the sewer and say we delivered it. Fry, you can’t just sit here in the dark listening to classical music. The alien mothership is in orbit here. If we can hit that bullseye, the rest of the dominoes will fall like a house of cards. Checkmate.\r\n\r\nFatal. Daddy Bender, we’re hungry. And so we say goodbye to our beloved pet, Nibbler, who’s gone to a place where I, too, hope one day to go. The toilet. Well, thanks to the Internet, I’m now bored with sex. Is there a place on the web that panders to my lust for violence?\r\n\r\n", "Episode 03: Dating As a Digital Nomad"),
    new PodcastResponse(Guid.NewGuid(), DateTime.Now, "https://themes.pixelwars.org/podcasty/demo-01/wp-content/uploads/sites/2/2020/11/b-04-550x550.jpg", "Perhaps, but perhaps your civilization is merely the sewer of an even greater society above you! I feel like I was mauled by Jesus. Stop! Don’t shoot fire stick in space canoe! Cause explosive decompression!\r\n\r\nWell, let’s just dump it in the sewer and say we delivered it. Fry, you can’t just sit here in the dark listening to classical music. The alien mothership is in orbit here. If we can hit that bullseye, the rest of the dominoes will fall like a house of cards. Checkmate.\r\n\r\nFatal. Daddy Bender, we’re hungry. And so we say goodbye to our beloved pet, Nibbler, who’s gone to a place where I, too, hope one day to go. The toilet. Well, thanks to the Internet, I’m now bored with sex. Is there a place on the web that panders to my lust for violence?\r\n\r\n", "Episode 02: Getting Rid Of Time Consuming Habits"),
    new PodcastResponse(Guid.NewGuid(), DateTime.Now, "https://travel.oceanwp.org/wp-content/uploads/2016/04/travel-blog-1.jpg", "Perhaps, but perhaps your civilization is merely the sewer of an even greater society above you! I feel like I was mauled by Jesus. Stop! Don’t shoot fire stick in space canoe! Cause explosive decompression!\r\n\r\nWell, let’s just dump it in the sewer and say we delivered it. Fry, you can’t just sit here in the dark listening to classical music. The alien mothership is in orbit here. If we can hit that bullseye, the rest of the dominoes will fall like a house of cards. Checkmate.\r\n\r\nFatal. Daddy Bender, we’re hungry. And so we say goodbye to our beloved pet, Nibbler, who’s gone to a place where I, too, hope one day to go. The toilet. Well, thanks to the Internet, I’m now bored with sex. Is there a place on the web that panders to my lust for violence?\r\n\r\n", "Episode 06: Rise of Nomad Destinations"),
    new PodcastResponse(Guid.NewGuid(), DateTime.Now, "https://themes.pixelwars.org/editor/wp-content/uploads/2015/05/slide-03-big.jpg", "Perhaps, but perhaps your civilization is merely the sewer of an even greater society above you! I feel like I was mauled by Jesus. Stop! Don’t shoot fire stick in space canoe! Cause explosive decompression!\r\n\r\nWell, let’s just dump it in the sewer and say we delivered it. Fry, you can’t just sit here in the dark listening to classical music. The alien mothership is in orbit here. If we can hit that bullseye, the rest of the dominoes will fall like a house of cards. Checkmate.\r\n\r\nFatal. Daddy Bender, we’re hungry. And so we say goodbye to our beloved pet, Nibbler, who’s gone to a place where I, too, hope one day to go. The toilet. Well, thanks to the Internet, I’m now bored with sex. Is there a place on the web that panders to my lust for violence?\r\n\r\n", "Episode 02: Getting Rid Of Time Consuming Habits"),
    new PodcastResponse(Guid.NewGuid(), DateTime.Now, "https://themes.pixelwars.org/editor/wp-content/uploads/2015/05/08.jpg", "Perhaps, but perhaps your civilization is merely the sewer of an even greater society above you! I feel like I was mauled by Jesus. Stop! Don’t shoot fire stick in space canoe! Cause explosive decompression!\r\n\r\nWell, let’s just dump it in the sewer and say we delivered it. Fry, you can’t just sit here in the dark listening to classical music. The alien mothership is in orbit here. If we can hit that bullseye, the rest of the dominoes will fall like a house of cards. Checkmate.\r\n\r\nFatal. Daddy Bender, we’re hungry. And so we say goodbye to our beloved pet, Nibbler, who’s gone to a place where I, too, hope one day to go. The toilet. Well, thanks to the Internet, I’m now bored with sex. Is there a place on the web that panders to my lust for violence?\r\n\r\n", "Episode 06: Rise of Nomad Destinations"),
    new PodcastResponse(Guid.NewGuid(), DateTime.Now, "https://themes.pixelwars.org/editor/wp-content/uploads/2015/05/06d.jpg", "Perhaps, but perhaps your civilization is merely the sewer of an even greater society above you! I feel like I was mauled by Jesus. Stop! Don’t shoot fire stick in space canoe! Cause explosive decompression!\r\n\r\nWell, let’s just dump it in the sewer and say we delivered it. Fry, you can’t just sit here in the dark listening to classical music. The alien mothership is in orbit here. If we can hit that bullseye, the rest of the dominoes will fall like a house of cards. Checkmate.\r\n\r\nFatal. Daddy Bender, we’re hungry. And so we say goodbye to our beloved pet, Nibbler, who’s gone to a place where I, too, hope one day to go. The toilet. Well, thanks to the Internet, I’m now bored with sex. Is there a place on the web that panders to my lust for violence?\r\n\r\n", "Episode 07: Goodbye boring, hello adventure"),
    new PodcastResponse(Guid.NewGuid(), DateTime.Now, "https://themes.pixelwars.org/photographer-html/images/album/06.jpg", "Perhaps, but perhaps your civilization is merely the sewer of an even greater society above you! I feel like I was mauled by Jesus. Stop! Don’t shoot fire stick in space canoe! Cause explosive decompression!\r\n\r\nWell, let’s just dump it in the sewer and say we delivered it. Fry, you can’t just sit here in the dark listening to classical music. The alien mothership is in orbit here. If we can hit that bullseye, the rest of the dominoes will fall like a house of cards. Checkmate.\r\n\r\nFatal. Daddy Bender, we’re hungry. And so we say goodbye to our beloved pet, Nibbler, who’s gone to a place where I, too, hope one day to go. The toilet. Well, thanks to the Internet, I’m now bored with sex. Is there a place on the web that panders to my lust for violence?\r\n\r\n", "Episode 04: The Digital Nomad Lifestyle Facts"),
    new PodcastResponse(Guid.NewGuid(), DateTime.Now, "https://themes.pixelwars.org/photographer-html/images/gallery/04.jpg", "Perhaps, but perhaps your civilization is merely the sewer of an even greater society above you! I feel like I was mauled by Jesus. Stop! Don’t shoot fire stick in space canoe! Cause explosive decompression!\r\n\r\nWell, let’s just dump it in the sewer and say we delivered it. Fry, you can’t just sit here in the dark listening to classical music. The alien mothership is in orbit here. If we can hit that bullseye, the rest of the dominoes will fall like a house of cards. Checkmate.\r\n\r\nFatal. Daddy Bender, we’re hungry. And so we say goodbye to our beloved pet, Nibbler, who’s gone to a place where I, too, hope one day to go. The toilet. Well, thanks to the Internet, I’m now bored with sex. Is there a place on the web that panders to my lust for violence?\r\n\r\n", "Episode 03: Dating As a Digital Nomad"),
    new PodcastResponse(Guid.NewGuid(), DateTime.Now, "https://themes.pixelwars.org/photographer-html/images/blog/blog-01.jpg", "Perhaps, but perhaps your civilization is merely the sewer of an even greater society above you! I feel like I was mauled by Jesus. Stop! Don’t shoot fire stick in space canoe! Cause explosive decompression!\r\n\r\nWell, let’s just dump it in the sewer and say we delivered it. Fry, you can’t just sit here in the dark listening to classical music. The alien mothership is in orbit here. If we can hit that bullseye, the rest of the dominoes will fall like a house of cards. Checkmate.\r\n\r\nFatal. Daddy Bender, we’re hungry. And so we say goodbye to our beloved pet, Nibbler, who’s gone to a place where I, too, hope one day to go. The toilet. Well, thanks to the Internet, I’m now bored with sex. Is there a place on the web that panders to my lust for violence?\r\n\r\n", "Episode 02: Getting Rid Of Time Consuming Habits"),
];

    }

    public async Task<ServiceResult<List<PodcastResponse>>> GetAllAsync(HttpContext context, CancellationToken cancellationToken, string? lang = "en-US")
    {
        return ServiceResult<List<PodcastResponse>>.Success(podcastList);
    }


    public async Task<ServiceResult<PodcastResponse>> GetByIdAsync(Guid id,HttpContext context, CancellationToken cancellationToken, string? lang = "en-US")
    {

        var podcast = podcastList.FirstOrDefault(x => x.Id == id);
        if (podcast == null)
        {
            return ServiceResult<PodcastResponse>.Failure("Podcast not found",statusCode:404);
        }

        return ServiceResult<PodcastResponse>.Success(podcast);
    }





}


