networks:
  main_network:
    external: true

services:

  digibanter.api:
    image: ${DOCKER_REGISTRY-}digibanterapi
    build:
      context: .
      dockerfile: DigiBanter.Api/Dockerfile
    networks:
      - main_network

