
services:

  parslinks.web:
    image: ${DOCKER_REGISTRY-}parslinks.web
    container_name: parslinks.web
    build:
      context: .
      dockerfile: ParsLinks.Web/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081

  parslinks.admin:
    image: ${DOCKER_REGISTRY-}parslinks.admin
    container_name: parslinks.admin
    build:
      context: .
      dockerfile: ParsLinks.Admin/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
 

  parslinks.api:
    image: ${DOCKER_REGISTRY-}parslinks.api
    container_name: parslinks.api
    build:
      context: .
      dockerfile: ParsLinks.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081











