networks:
  main_network:
    external: true

services:

  parslinks.api:
    image: ${DOCKER_REGISTRY-}parslinksapi
    container_name: parslinks.api
    build:
      context: .
      dockerfile: ParsLinks.Api/Dockerfile
    networks:
      - main_network

