networks:
  main_network:
    external: true

services:

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    command: ["start"]
    environment:

      KC_HOSTNAME: ${KEYCLOAK_HOSTNAME}
      KC_HTTP_ENABLED: true        # Enable HTTP
      KC_HTTPS_PORT: 8443
      KC_HOSTNAME_STRICT_BACKCHANNEL: true
      KC_HEALTH_ENABLED: true
      KC_METRICS_ENABLED: true
      KC_DB: postgres
      KC_DB_URL: ${KEYCLOAK_DB_URL}
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_PROXY: edge
      KC_LOG_LEVEL: info
      #KC_HTTPS_CERTIFICATE_FILE: /etc/x509/https/tls.crt
      #KC_HTTPS_CERTIFICATE_KEY_FILE: /etc/x509/https/tls.key
    ports:
      - "3000:8080"
      - "3001:8443"
      - "3002:9000"

    restart: unless-stopped
    networks:
      - main_network







