name: Build and Push Docker Images

on:
  push:
    branches:
      - master  # Trigger on push to main but with commit message filtering

jobs:
  build-and-push:
    if: contains(github.event.head_commit.message, '#build')  # Run if commit message contains #release
    runs-on: ubuntu-latest

    env:
      REGISTRY: ghcr.io
      IMAGE_WEB: yaghmori/digibanter.web
      IMAGE_API: yaghmori/digibanter.api
      TAG: latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose -y

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PASS }}

      - name: Build Docker Images
        run: |
          docker-compose -f docker-compose.prod.yml build

      - name: Tag Docker Images
        run: |
          docker tag digibanter.web ${{ env.REGISTRY }}/${{ env.IMAGE_WEB }}:${{ env.TAG }}
      - name: Push Docker Images
        run: |
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_WEB }}:${{ env.TAG }}
